sudo: required #is required to use docker service in travis

language: php #can be any language, just php for example

services:
  - docker # required, but travis uses older version of docker :(

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - echo "no tests!" # put your normal testing scripts here

after_success:
  - docker --version  # document the version travis is using
  - cd docker
  - docker build -t docker pull kappavita/projectcs18:latest .
  - docker push kappavita/projectcs18:latest
  #- docker tag my_example_app:latest [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/my_example_app:latest
  #- docker push [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/my_example_app:latest
  
# sadly, travis doesn't cache docker builds yet, so each build will take a while
