sudo: required
language: php
services:
- docker
install:
- echo "install nothing!"
script:
- echo "no tests!"
after_success:
- docker --version
- cd docker
- docker login -p=$DOCKER_PASS -u=$DOCKER_USER
- docker build -t kappavita/projectcs18:latest .
- docker push kappavita/projectcs18:latest
env:
  global:
  - secure: wHmbmgStVGfipXlMVEm4LAApr4iojnZj18Df4+9J1rh6eDBFrwQec/9EmGQBCaF9MiXo4uhWHHqm9+eMWYUQ8N0SaYj2HMkER3X9PhhPBIDPVXHwUADC9NwL1q3jyQGXGcXpTnwnggNdY6UBsJ6Q89s81MYVarNf0OyElFwu0V3BOwgRgjpMOuQ3scoIJVfcHO2/AZUxJb5oeizveP6SZr61h/hTqFu+KcRPqg90SN7uUihi7dEWqcYmUpFh6Yb73cXO6BdQ/vFrj1da4nwDTaA7N9QO8t1BK2RVWk9KTb4YRFDXmxa/4vbBzjkkdMb9tzTuVkjJM/7uPPu4FG95XjMha+cfnZ7WJlbgeDq3QjRZGIRzJuIKg+MvCPGn313QffhkKCuRbtK2RxrbHUDbOGocKZeEuCxfFvVMP+5CRorCVHshSKV2T3NEWBkSX8XB5pLmXAQRBtb/GS2BMwVSEboJoo+qrgoCk0BptMmBINxYG4NesAULYI1zqGzc7CtKTLu0mEJJIk8I1Lm3RmpAzkvEluJ6x7f8PMgyR4OP48sQGTjgvFSKnTkkgLIAdEfnx5NiP65TAUBHeGHMBCZJ4U2uyBvVk0hj8MJBfWXJqYMdzU2SZnB6siv7jTZVKX20tkVMOajaUqsdYlgJEIMC0Vk3cc7sXfpQxhl8GX5SZ+Q=
  - secure: Pv/mENt1g0T80pHsEniQgC0sUph8VXhL/JmY1HeqHjf8PQ4932s+D2JXfAbgB5fdWlCvtGclC7ZoR5uY4k8qaDjKaIBCXjyOBhhb/mBfcrCq3leA+TrW01db1/KIzFKuza2MMVPZ4YcokmYqbVFKtIlOQJi8XEc7Nge6jggNEZ1TMuPcLRa05kKA/Jy6IAkf5rOPYJ7ElTD+/90ebr4CnCBc+vPWZW9Yx8LMmS8l+J0JtWrZdsTcsaOo9fXNB1sGC6BWCr4GYHQ80U6WBAN61mQt5NMtfw3Ij8JVYJySIp7sxpVpTsNHTRDXabT/CGYpFQewhMDR7Ffx3UEk+jEDyx8+tUDOltmyS4HErFx9lHRms2HDPc4cY8xxY7MuR74AW38eNX6csZVms2058XwW6QwoVvobzvjCiFp3zGUIxIn4GOzhu1QAice9tvCod+d6jGIjwVYzomghTRfonTsAJ2/UZDruEf1QB2xPoSzt8upy8owpJWS8aOO2ODaQt1X4GA06Rq/uEp8J1/iFLmHf+YdQWOJonbb+TSoAmljVxIcnGJap8Xs/c2wLuR9p2lYDTBfEd0uQErShJCF7W3cUKynuua9RmW1q24fdCoGsKII5oo/F2vIwDGnCgH94C5ahIOt4WJb/lfaaZIHXJMK5XDXJe2VqoTOs01tfOQlrlKQ=
